### ISSUE TITLE
#1 As a guest I want to view the talent list to see general information about talents:

### ISSUE THREAD

**Issue by KOSMOSq** [Team-Olya/frontend#17]
As a guest I want to view the talent list to see general information about talents:
On the main page I want to see a list of talents with general information:
Avatar
Full Name
Kind of talent
I want to be able to choose the way of displaying the list of talents.
I want to have the functionality of paging the list of talents.

As a guest, I would like to view a list of talents on the main page, with the following general information displayed for each talent:
Avatar
Full name
Kind of talent
- I would like to have the option to choose the way in which the list of talents is displayed
- I would also like the ability to page through the list of talents.

### Front tasks: 
- [x] #11
- [x] #12
- [x] #13 
- [x] #14 
- [x] #15 
- [x] #16  

### Back tasks: 
- [x] https://github.com/Team-Olya/backend/issues/4
- [x] https://github.com/Team-Olya/backend/issues/5

**Comment by lyuben1337** [comment]
Hi

**Comment by monrit** [comment]
А якщо я напишу комента
